version: '3.7'

services:
  jekyll:
    build: .
    command: [ "sh", "-c", "npm ci && bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling" ]
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/_site
      - /srv/jekyll/.jekyll-cache
      - /srv/jekyll/node_modules
