version: '3.7'

services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --livereload --force_polling --incremental
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/_site
      - /srv/jekyll/.jekyll-cache
